[package]
name = "serve"
version = "0.1.0"
edition = "2018"

[dependencies]
ansi_term = "0.12"
clap = "3.0.0-beta.4"
clipboard = "0.5"
local-ip-address = "0.4"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
